version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "cargo"
    directory: "/xtask"
    schedule:
      interval: "weekly"

  - package-ecosystem: "cargo"
    directory: "/crates/coffyaml"
    schedule:
      interval: "weekly"

  - package-ecosystem: "cargo"
    directory: "/crates/jamcrc"
    schedule:
      interval: "weekly"

  - package-ecosystem: "cargo"
    directory: "/crates/jamcrc/cli"
    schedule:
      interval: "weekly"

  - package-ecosystem: "cargo"
    directory: "/crates/objs2yaml"
    schedule:
      interval: "weekly"
