name: CI

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    name: Run CI tasks
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install clippy and rustfmt
        run: |
          rustup update
          rustup component add clippy rustfmt

      - run: cargo xtask ci
